/*
 * Copyright (c) 2012, Codename One and/or its affiliates. All rights reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 * This code is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License version 2 only, as
 * published by the Free Software Foundation.  Codename One designates this
 * particular file as subject to the "Classpath" exception as provided
 * by Oracle in the LICENSE file that accompanied this code.
 *
 * This code is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 * version 2 for more details (a copy is included in the LICENSE file that
 * accompanied this code).
 *
 * You should have received a copy of the GNU General Public License version
 * 2 along with this work; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 * Please contact Codename One through http://www.codenameone.com/ if you
 * need additional information or have any questions.
 */

package com.codename1.store;


import com.codename1.rad.controllers.ApplicationController;
import com.codename1.rad.controllers.ControllerEvent;
import com.codename1.rad.controllers.FormController;
import com.codename1.rad.models.Entity;
import com.codename1.rad.nodes.ActionNode;
import com.codename1.rad.nodes.Node;
import com.codename1.rad.nodes.ViewNode;
import com.codename1.rad.ui.UI;
import com.codename1.store.controllers.OnBoardingController;
import com.codename1.store.models.OnBoardingModel;
import com.codename1.store.views.OnBoardingView;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename One</a> for the purpose 
 * of building native mobile applications using Java.
 */
public class Store extends ApplicationController {

    public static final ActionNode logInAction = UI.action();
    public static final ActionNode signUpAction = UI.action();
    public static final ActionNode facebookAction = UI.action();
    public static final ActionNode googleAction = UI.action();
    public static final ActionNode appleAction = UI.action();

    @Override
    public void actionPerformed(ControllerEvent evt) {
        if (evt instanceof StartEvent) {
            evt.consume();

            FormController onBoardingController = new OnBoardingController(this, createDemoOnBoardingEntity(), createDemoOnBoardingNode());
            onBoardingController.getView().show();

            addActionListener(logInAction, event->{
                event.consume();
                System.out.println("login Pressed");
            });

            addActionListener(signUpAction, event->{
                event.consume();
                System.out.println("sign up Pressed");
            });

            addActionListener(googleAction, event->{
                event.consume();
                System.out.println("google Pressed");
            });

            addActionListener(facebookAction, event->{
                event.consume();
                System.out.println("facebook Pressed");
            });

            addActionListener(appleAction, event->{
                event.consume();
                System.out.println("apple Pressed");
            });
        }

    }

    private Entity createDemoOnBoardingEntity(){
        return new OnBoardingModel(
                "https://sergeycodenameone.github.io/demo-logo.png",
                "https://sergeycodenameone.github.io/first-intro-image.png",
                "https://sergeycodenameone.github.io/first-intro-image.png",
                "https://sergeycodenameone.github.io/first-intro-image.png",
                "Onboarding Slide 1",
                "Onboarding Slide 2",
                "Onboarding Slide 3",
                "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
                "Lorem Ipsum is simply dummy text of the printing and typesetting industry"
        );
    }

    private Node createDemoOnBoardingNode(){
        return new ViewNode(
                UI.actions(OnBoardingView.LOGIN_BUTTON, logInAction),
                UI.actions(OnBoardingView.SIGN_UP_BUTTON, signUpAction),
                UI.actions(OnBoardingView.FACEBOOK_BUTTON, facebookAction),
                UI.actions(OnBoardingView.GOOGLE_BUTTON, googleAction),
                UI.actions(OnBoardingView.APPLE_BUTTON, appleAction)
        );
    }
}
